import type { ComponentType } from 'react';
import {
	SiUber,
	SiLyft,
	SiDoordash,
	SiInstacart,
	SiGrubhub,
	SiUbereats,
	SiUpwork,
	SiFiverr,
	SiFreelancer,
	SiToptal,
	SiYoutube,
	SiTwitch,
	SiPatreon,
	SiOnlyfans,
	SiSubstack,
	SiAirbnb,
	SiStripe,
	SiSquare,
	SiVenmo,
	SiPaypal,
	SiZelle,
	SiCashapp,
} from 'react-icons/si';

export const PLATFORM_ICONS: Record<string, ComponentType<{ className?: string }>> = {
	Uber: SiUber,
	Lyft: SiLyft,
	DoorDash: SiDoordash,
	Instacart: SiInstacart,
	Grubhub: SiGrubhub,
	'Uber Eats': SiUbereats,
	UberEats: SiUbereats,
	Upwork: SiUpwork,
	Fiverr: SiFiverr,
	Freelancer: SiFreelancer,
	Toptal: SiToptal,
	YouTube: SiYoutube,
	Twitch: SiTwitch,
	Patreon: SiPatreon,
	OnlyFans: SiOnlyfans,
	Substack: SiSubstack,
	Airbnb: SiAirbnb,
	Stripe: SiStripe,
	Square: SiSquare,
	Venmo: SiVenmo,
	PayPal: SiPaypal,
	Zelle: SiZelle,
	'Cash App': SiCashapp,
};
